replicaCount: 1

image:
  repository: backend-volume
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets:
  - name: regcred

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext:
  fsGroup: 2000

securityContext:
  runAsUser: 1000
  runAsGroup: 3000

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  dnsWildcard: development.krci-dev.cloudmentor.academy
  className: ""
  annotations: {}
  hosts:
    - host: edpDefault
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

livenessProbe:
  tcpSocket:
    port: 8080
readinessProbe:
  tcpSocket:
    port: 8080
  initialDelaySeconds: 20

autoscaling:
  enabled: false

nodeSelector: {}
tolerations: []
affinity: {}
